# Generated by Django 5.0.2 on 2024-12-14 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitytype',
            name='fa_id',
            field=models.IntegerField(unique=True, verbose_name='FA ID'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='fa_id',
            field=models.IntegerField(unique=True, verbose_name='FA ID'),
        ),
        migrations.AlterField(
            model_name='group',
            name='fa_id',
            field=models.IntegerField(unique=True, verbose_name='FA ID'),
        ),
    ]
