# Generated by Django 5.0.2 on 2024-11-29 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_students', '0002_group_message_notification_telegramaccount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': 'Уведомление', 'verbose_name_plural': 'Уведомления'},
        ),
        migrations.AlterModelOptions(
            name='telegramaccount',
            options={'verbose_name': 'Телеграм аккаунт', 'verbose_name_plural': 'Телеграм аккаунты'},
        ),
    ]
