# Generated by Django 5.0.2 on 2024-12-16 20:13

import api_students.models.university
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_students', '0003_alter_student_telegram_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='schedule_date',
            new_name='schedule_datetime',
        ),
        migrations.AlterField(
            model_name='group',
            name='code',
            field=models.CharField(max_length=50, unique=True, validators=[api_students.models.university.validate_group], verbose_name='Код группы'),
        ),
    ]
