# Generated by Django 5.0.2 on 2024-12-03 23:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_students', '0004_group_created_at_alter_group_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentrecord',
            name='discipline',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='notification',
            name='group',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='message',
            name='group',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='telegramaccount',
            name='group',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='studentrecord',
            name='type_activity',
            field=models.CharField(max_length=150),
        ),
        migrations.DeleteModel(
            name='Discipline',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='TypeActivity',
        ),
    ]
