# Generated by Django 5.0.2 on 2024-12-18 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_students', '0004_rename_schedule_date_message_schedule_datetime_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasswordReset',
        ),
    ]
