# Generated by Django 5.0.2 on 2024-12-03 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_students', '0005_alter_studentrecord_discipline_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='studentrecord',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='records', to='api_students.student'),
        ),
        migrations.DeleteModel(
            name='TelegramAccount',
        ),
    ]
