# Generated by Django 5.0.2 on 2024-12-30 11:08

import api_students.models.students
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_students', '0006_alter_student_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='username',
            new_name='fa_login',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='password',
            new_name='fa_password',
        ),
        migrations.AlterField(
            model_name='message',
            name='is_sent',
            field=models.BooleanField(default=False, verbose_name='Отправлено'),
        ),
        migrations.AlterField(
            model_name='student',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Полное имя'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, max_length=16, null=True, validators=[api_students.models.students.validate_whatsapp_number], verbose_name='Телефон (WhatsApp)'),
        ),
    ]
