# Generated by Django 5.0.2 on 2025-01-01 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_students', '0007_rename_username_student_fa_login_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='time_end',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='time_start',
            new_name='start_time',
        ),
        migrations.RemoveField(
            model_name='studentrecord',
            name='date',
        ),
        migrations.RemoveField(
            model_name='studentrecord',
            name='time_end',
        ),
        migrations.RemoveField(
            model_name='studentrecord',
            name='time_start',
        ),
        migrations.AlterField(
            model_name='activity',
            name='marked_as_proctoring',
            field=models.BooleanField(default=False, verbose_name='Установлена как прокторинг'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='marked_by_students_as_proctoring',
            field=models.BooleanField(default=False, verbose_name='Помечена студентами как прокторинг'),
        ),
        migrations.AlterField(
            model_name='student',
            name='full_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Полное имя'),
        ),
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_students.group', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='student',
            name='telegram_id',
            field=models.IntegerField(default=1, verbose_name='Telegram ID'),
            preserve_default=False,
        ),
    ]
