# Generated by Django 5.0.2 on 2025-01-01 21:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_students', '0008_rename_time_end_activity_end_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructionForProctoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст инструкции')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'avi', 'mkv'])], verbose_name='Видео инструкция')),
                ('file', models.FileField(blank=True, null=True, upload_to='files/', verbose_name='Файл инструкции')),
            ],
        ),
    ]
