# Generated by Django 5.0.2 on 2025-01-01 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_students', '0009_instructionforproctoring'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Текст')),
            ],
        ),
    ]
