# Generated by Django 5.0.2 on 2025-01-06 17:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_students', '0012_student_is_blocked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='code',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='code',
            name='code',
        ),
        migrations.RemoveField(
            model_name='code',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='message',
            name='group',
        ),
        migrations.AddField(
            model_name='code',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата получения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='code',
            name='status',
            field=models.CharField(choices=[('used', 'Использован'), ('active', 'Активный')], default='active', max_length=10, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='code',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_students.student'),
        ),
        migrations.AddField(
            model_name='code',
            name='value',
            field=models.CharField(default=django.utils.timezone.now, max_length=250, unique=True, verbose_name='Значение'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='receiver',
            field=models.CharField(default=1, max_length=250, verbose_name='Получатель'),
            preserve_default=False,
        ),
    ]
