# Generated by Django 5.0.2 on 2025-01-26 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_students', '0015_remove_message_receiver_message_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
    ]
