# Generated by Django 5.0.2 on 2025-01-27 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_students', '0017_alter_student_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='telegram_id',
            field=models.BigIntegerField(verbose_name='Telegram ID'),
        ),
    ]
