# Generated by Django 5.0.2 on 2024-05-19 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_auction', '0001_initial'),
        ('api_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='customer_manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='api_users.customermanager', verbose_name='Менеджер Заказчика'),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='transporter_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='api_users.transportermanager', verbose_name='Менеджер Перевозчика'),
        ),
        migrations.AddField(
            model_name='orderdocument',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='api_auction.ordermodel', verbose_name='Заказ'),
        ),
        migrations.AddField(
            model_name='orderoffer',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='api_auction.ordermodel', verbose_name='Заказ'),
        ),
        migrations.AddField(
            model_name='orderoffer',
            name='transporter_manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='api_users.transportermanager', verbose_name='Перевозчик'),
        ),
        migrations.AddField(
            model_name='orderstagecouple',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='api_auction.ordermodel', verbose_name='Заказ'),
        ),
        migrations.AddField(
            model_name='orderloadstage',
            name='order_couple',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='load_stage', to='api_auction.orderstagecouple', verbose_name='Поставка'),
        ),
        migrations.AddField(
            model_name='ordertracking',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tracking', to='api_auction.ordermodel', verbose_name='Заказ'),
        ),
        migrations.AddField(
            model_name='ordertrackinggeopoint',
            name='tracking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geopoints', to='api_auction.ordertracking', verbose_name='Отслеживание'),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='transport_body_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_auction.ordertransportbodytype', verbose_name='Тип кузова транспорта'),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='transport_load_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_auction.ordertransportloadtype', verbose_name='Тип загрузки транспорта'),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='transport_unload_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_auction.ordertransportunloadtype', verbose_name='Тип выгрузки транспорта'),
        ),
        migrations.AddField(
            model_name='orderunloadstage',
            name='order_couple',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='unload_stage', to='api_auction.orderstagecouple', verbose_name='Поставка'),
        ),
    ]
