# Generated by Django 5.0.2 on 2024-07-08 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_auction', '0002_initial'),
        ('api_users', '0002_remove_driverprofile_company_driverprofile_companies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='api_users.driverprofile', verbose_name='Водитель'),
        ),
    ]
