# Generated by Django 5.0.2 on 2024-07-19 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_auction', '0003_ordermodel_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderloadstage',
            name='city',
            field=models.CharField(default=1, max_length=100, verbose_name='Город'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderloadstage',
            name='postal_code',
            field=models.CharField(default=1, max_length=20, verbose_name='Почтовый индекс'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderunloadstage',
            name='city',
            field=models.CharField(default=1, max_length=100, verbose_name='Город'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderunloadstage',
            name='postal_code',
            field=models.CharField(default='default', max_length=20, verbose_name='Почтовый индекс'),
            preserve_default=False,
        ),
    ]
