# Generated by Django 5.0.2 on 2024-07-20 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_auction', '0004_orderloadstage_city_orderloadstage_postal_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderApplicationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('in_auction', 'Аукцион'), ('in_bidding', 'Торги'), ('in_direct', 'Прямой заказ')], max_length=300, verbose_name='Тип заявки')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api_auction.ordermodel', verbose_name='Заказ')),
            ],
        ),
    ]
