# Generated by Django 5.0.2 on 2024-07-20 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_auction', '0005_orderapplicationtype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderapplicationtype',
            old_name='type',
            new_name='status',
        ),
        migrations.AlterField(
            model_name='orderapplicationtype',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='application_type', to='api_auction.ordermodel', verbose_name='Заказ'),
        ),
    ]
