# Generated by Django 5.0.2 on 2024-07-30 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_auction', '0006_rename_type_orderapplicationtype_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderloadstage',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='orderloadstage',
            name='volume',
        ),
        migrations.RemoveField(
            model_name='orderloadstage',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='orderunloadstage',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='orderunloadstage',
            name='volume',
        ),
        migrations.RemoveField(
            model_name='orderunloadstage',
            name='weight',
        ),
        migrations.AddField(
            model_name='orderstagecouple',
            name='cargo',
            field=models.CharField(default=1, max_length=300, verbose_name='Груз'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderstagecouple',
            name='volume',
            field=models.PositiveIntegerField(default=1, verbose_name='Объем'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderstagecouple',
            name='weight',
            field=models.PositiveIntegerField(default=1, verbose_name='Вес'),
            preserve_default=False,
        ),
    ]
