# Generated by Django 5.0.2 on 2024-07-30 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_auction', '0007_remove_orderloadstage_cargo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderloadstage',
            name='comments',
            field=models.TextField(blank=True, max_length=20000, null=True, verbose_name='Комментарии к поставке'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='additional_requirements',
            field=models.TextField(blank=True, max_length=20000, null=True, verbose_name='Дополнительные требования'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='adr',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ADR [шт.]'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='comments_for_transporter',
            field=models.TextField(blank=True, max_length=20000, null=True, verbose_name='Комментарии для перевозчика'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='temp_mode',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Температурный режим'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='transport_body_height',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Высота кузова'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='transport_body_length',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Длина кузова'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='transport_body_width',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Ширина кузова'),
        ),
        migrations.AlterField(
            model_name='orderunloadstage',
            name='comments',
            field=models.TextField(blank=True, max_length=20000, null=True, verbose_name='Комментарии к поставке'),
        ),
    ]
