# Generated by Django 5.0.2 on 2024-08-12 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_auction', '0008_alter_orderloadstage_comments_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordermodel',
            options={'ordering': ['transportation_number'], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='adr',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ADR'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Время обновления'),
        ),
    ]
