# Generated by Django 5.0.2 on 2024-08-14 15:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_auction', '0010_alter_ordermodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='transport_body_height',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Высота кузова'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='transport_body_length',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Длина кузова'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='transport_body_width',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Ширина кузова'),
        ),
        migrations.AlterField(
            model_name='orderstagecouple',
            name='volume',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Объем'),
        ),
        migrations.AlterField(
            model_name='orderstagecouple',
            name='weight',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Вес'),
        ),
    ]
