# Generated by Django 5.0.2 on 2024-07-08 10:36

import api_users.models.profiles
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverprofile',
            name='company',
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='companies',
            field=models.ManyToManyField(related_name='drivers', to='api_users.transportercompany'),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='phone_number',
            field=models.CharField(default=77777777777, max_length=17, validators=[api_users.models.profiles.PhoneNumberValidator()], verbose_name='Телефон'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
