# Generated by Django 5.0.2 on 2024-07-08 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_users', '0002_remove_driverprofile_company_driverprofile_companies_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FullNameModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=300)),
            ],
        ),
        migrations.RemoveField(
            model_name='driverprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='content_type',
            field=models.ForeignKey(default=1, limit_choices_to={'model__in': ('usermodel', 'fullnamemodel')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
