# Generated by Django 5.0.2 on 2024-07-11 09:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_users', '0003_fullnamemodel_remove_driverprofile_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordReset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('token', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='birth_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='machine_data',
            field=models.CharField(max_length=300, verbose_name='Данные авто'),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='machine_number',
            field=models.CharField(max_length=20, verbose_name='Номер авто'),
        ),
        migrations.AlterField(
            model_name='fullnamemodel',
            name='full_name',
            field=models.CharField(max_length=300, verbose_name='ФИО'),
        ),
    ]
