# Generated by Django 5.0.2 on 2024-08-18 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_users', '0007_alter_driverprofile_phone_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FullNameModel',
        ),
        migrations.RemoveField(
            model_name='driverprofile',
            name='companies',
        ),
        migrations.RemoveField(
            model_name='driverprofile',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='driverprofile',
            name='object_id',
        ),
    ]
