# Generated by Django 5.0.2 on 2024-08-18 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_users', '0009_driverprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='email',
            field=models.EmailField(blank=True, max_length=300, null=True, unique=True, verbose_name='Электронная почта'),
        ),
    ]
