# Generated by Django 5.0.2 on 2024-08-20 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_users', '0010_alter_usermodel_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneNumberChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_phone_number', models.CharField(max_length=15)),
                ('confirmation_code', models.CharField(max_length=4)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api_users.driverprofile')),
            ],
        ),
    ]
