# Generated by Django 5.0.2 on 2024-08-20 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_users', '0011_phonenumberchangerequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverprofile',
            name='machine_data',
            field=models.CharField(max_length=300, verbose_name='Машина'),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='machine_number',
            field=models.CharField(max_length=20, unique=True, verbose_name='Номер машины'),
        ),
    ]
