# Generated by Django 5.0.2 on 2024-08-27 14:37

import api_users.models.profiles
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_users', '0012_alter_driverprofile_machine_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=100, validators=[api_users.models.profiles.PhoneNumberValidator()], verbose_name='Телефон поддержки')),
            ],
            options={
                'verbose_name': 'Настройка',
                'verbose_name_plural': 'Настройки',
            },
        ),
    ]
