# Generated by Django 5.0.2 on 2024-08-30 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_users', '0015_customersubscription_transportersubscription_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='blocked',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='has_unpaid_subscription',
            field=models.BooleanField(default=False, verbose_name='Тариф не оплачен'),
        ),
    ]
