# Generated by Django 5.0.2 on 2024-08-30 22:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_users', '0016_remove_usermodel_blocked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersubscription',
            name='days_without_payment',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество дней без оплаты'),
        ),
        migrations.AlterField(
            model_name='customersubscription',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='transportersubscription',
            name='days_without_payment',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество дней без оплаты'),
        ),
        migrations.AlterField(
            model_name='transportersubscription',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Стоимость'),
        ),
    ]
