# Generated by Django 5.0.2 on 2024-09-01 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_users', '0017_alter_customersubscription_days_without_payment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverRegisterRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=17, unique=True)),
                ('confirmation_code', models.CharField(max_length=4)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='phonenumberchangerequest',
            name='new_phone_number',
            field=models.CharField(max_length=17),
        ),
    ]
