# Generated by Django 5.0.2 on 2024-09-01 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_users', '0018_driverregisterrequest_alter_driverprofile_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='email',
            field=models.EmailField(blank=True, max_length=300, null=True, verbose_name='Электронная почта'),
        ),
    ]
