# Generated by Django 5.0.2 on 2024-09-03 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_users', '0021_settings_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='has_unpaid_subscription',
            field=models.BooleanField(default=True, verbose_name='Тариф не оплачен'),
        ),
    ]
