# Generated by Django 5.0.2 on 2024-09-03 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_users', '0023_remove_usermodel_has_unpaid_subscription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='full_name',
            field=models.CharField(max_length=200, verbose_name='Полное имя'),
        ),
    ]
