# Generated by Django 5.0.2 on 2024-09-12 05:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_users', '0025_remove_usermodel_subscription_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customercompany',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_company', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
