# Generated by Django 5.0.2 on 2024-10-10 22:21

import api_users.models.profiles
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_users', '0026_alter_customercompany_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationForRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Имя')),
                ('email', models.EmailField(max_length=300, verbose_name='Email')),
                ('phone_number', models.CharField(max_length=17, validators=[api_users.models.profiles.PhoneNumberValidator()], verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Заявки на регистрацию',
            },
        ),
    ]
