# Generated by Django 5.0.2 on 2024-08-15 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_notification', '0003_notification_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['created_at'], 'verbose_name': 'Уведомление', 'verbose_name_plural': 'Уведомления'},
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('info', 'Информационная'), ('new_order_in_auction', 'Новый заказ в аукционе'), ('new_order_in_bidding', 'Новый заказ в торгах'), ('new_order_in_direct', 'Новый заказ назначен напрямую'), ('new_order_being_executed', 'Новый заказ принят в исполнение'), ('order_cancelled', 'Заказ отменен')], max_length=24, verbose_name='Тип'),
        ),
    ]
