# Generated by Django 5.0.2 on 2024-08-29 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_notification', '0004_alter_notification_options_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('info', 'Информационная'), ('new_order_in_auction', 'Новый заказ в аукционе'), ('new_order_in_bidding', 'Новый заказ в торгах'), ('new_order_in_direct', 'Новый заказ назначен напрямую'), ('new_order_being_executed', 'Новый заказ принят в исполнение'), ('order_cancelled', 'Заказ отменен'), ('popup_notification', 'Всплывающее уведомление')], max_length=24, verbose_name='Тип'),
        ),
    ]
