# Generated by Django 5.0.2 on 2024-08-30 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_notification', '0005_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='description',
            field=models.TextField(max_length=500, verbose_name='Описание'),
        ),
    ]
